### ISSUE TITLE
Async Validating Form allows submitting incorrect data 

### ISSUE THREAD

**Issue by utkez** [alsiola/form-and-function#8]
Async Validating Form on the example page (https://alsiola.github.io/form-and-function/) allows the user to submit incorrect data if he changes valid data to invalid and submits quickly.

Steps to reproduce:
1) Enter correct data (eg., qwerty) and wait till the validation is successful.
2) Change data to invalid (eg., qwe) and submit immediately.

Result: "Submitted with values" in the console.
Expected behavior: Wait till async validation is complete and return error "Submission failed"

**Comment by alsiola** [comment]
Hi @utkez, thanks for the feedback.  Dealing with ongoing validation at the time of submission is something I have thought about quite a bit, and I don't think there is necessarily a correct answer to how to handle it, so I would welcome your thoughts (and others) about this part of the API.

form-and-function currently passes an `isValidating` prop to the form renderer, which could be used to stop submission if validation is ongoing.  This puts the responsibility totally in the hands of the library consumer, which may lead to errors (such as in the examples, where I forgot to do it!).

Another option is to not allow form submission at all while validating, and call the `onSubmitFailed` callback instead.  This would work, but do consumers of the library expect there to be validation errors when this callback is invoked?  

The final option, which might be my preferred option, is to prevent submission while validating by default, and call the `onSubmitFailed` callback, but modify this callback slightly.  Currently it receives the form's values, this could be altered so it received the form's values, validation errors, and ongoing validation status, i.e.

Instead of:

`(formValues: FieldMap) => void`

have:

`(formValues: FieldMap, validationErrors: ValidationMap, isValidating: boolean) => void`

Potentially this behaviour could be modified with a prop passed to Form, such as `allowSubmissionWhileValidating`.

What are your thoughts on these different approaches?

**Comment by alsiola** [comment]
The demo bug is resolved so I'm closing this. If there is any desire to discuss the issue further then feel free to open a new issue.
